# Generated by Django 3.0.3 on 2020-02-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestoon', '0003_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='text',
            field=models.CharField(max_length=256),
        ),
    ]
